### ISSUE TITLE
Suggestion: Get osticket by release version instead of repo link.

### ISSUE THREAD

**Issue by yurividal** [rinkp/osticket-dockerized#2]
If you get OSTicket from the release version, using github tags, it's probably a more consistent way of getting the version,
Something like this:

````
ENV OSTICKET_VERSION=v1.17.2
RUN git clone -b ${OSTICKET_VERSION} --depth 1 https://github.com/osTicket/osTicket.git
````

This will allow a more consistent version tag. It will also ensure that the Admin Dashboard shows the right version, instead of a commit number. 
Perhaps you can create a -dev branch which uses your current method. 

This is by far the cleanest and best osticket docker image with apache out there, and it has a lot of pottential to become the "unofficial-official" image, since the developers of osticket refuse do use docker themselves. 

Thanks for your work.

Also, consider putting a link on dockerhub to this repo, so that more people can find it and contribute.

**Comment by rinkp** [comment]
> It will also ensure that the Admin Dashboard shows the right version, instead of a commit number.

I don't think that would be achieved by cloning the repo at the tag; as you may have seen, that specific commit is already checked out in the current way. A few things are added to the release version, see [include/cli/modules/deploy.php](https://github.com/osTicket/osTicket/blob/develop/include/cli/modules/deploy.php)

Although I agree it is undesirable, I have added hotfixes in the past (e.g. 23595372210506f798856c269d351ab9d63518f7) to make sure only working versions are published. Then, it may actually be more complicated to find the right commit. I will look into the option of using the `deploy.php` script or parts thereof.

> Also, consider putting a link on dockerhub to this repo, so that more people can find it and contribute.

Thanks, will do

**Comment by yurividal** [comment]
I can confirm that, using my method you get a version in the about page, as seen in the screenshot bellow. 

<img width="360" alt="image" src="https://user-images.githubusercontent.com/8555749/216783208-68e2fc6d-c323-43e0-93ce-796955666cb0.png">

But again, this is just a suggestion.
